# -*- coding: utf-8 -*-
"""Personality Trait Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JoTqEG2zMaQTPxLm4Uw0VtPvvB8QpEXD

# Personality Trait Analysis

# Importing necessary Python libraries.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""# Creating The Data Frame"""

df = pd.read_csv('/content/personality_synthetic_dataset.csv')

"""# Data Cleaning"""

df.head()

df.tail()

"""# Exploratory Data Analysis (EDA)"""

df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

df.drop_duplicates(inplace=True)

df.fillna(method='ffill', inplace=True)

df.info()

df.describe()

for col in df.select_dtypes(include='object').columns:
    print(f"\n{col}:\n", df[col].value_counts())

df.isnull().sum()

"""# Data Visualizations

# Distribution of Personality Types
"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(6, 4))
sns.countplot(x='personality_type', data=df, palette='Set2')
plt.title('Distribution of Personality Types')
plt.xlabel('Personality Type')
plt.ylabel('Count')
plt.tight_layout()
plt.show()

features = ['talkativeness', 'empathy', 'leadership', 'risk_taking']
for feature in features:
    plt.figure(figsize=(8, 4))
    sns.boxplot(x='personality_type', y=feature, data=df, palette='pastel')
    plt.title(f'{feature.capitalize()} by Personality Type')
    plt.tight_layout()
    plt.show()

plt.figure(figsize=(8, 5))
sns.kdeplot(data=df, x="social_energy", hue="personality_type", fill=True, alpha=0.6)
plt.title("Distribution of Social Energy by Personality Type")
plt.xlabel("Social Energy")
plt.ylabel("Density")
plt.tight_layout()
plt.show()

"""# Correlation Heatmap of Personality Traits"""

corr = df.drop(columns=['personality_type']).corr()

plt.figure(figsize=(18, 14))
sns.heatmap(corr, cmap='coolwarm', center=0, linewidths=0.5)
plt.title("Correlation Heatmap of Personality Traits", fontsize=16)
plt.tight_layout()
plt.show()

"""# Pairplot of Selected Traits by Personality Type"""

selected = ['social_energy', 'empathy', 'creativity', 'talkativeness', 'personality_type']
sns.pairplot(df[selected], hue='personality_type', palette='husl')
plt.suptitle("Pairplot of Selected Traits by Personality Type", y=1.02)
plt.show()

"""# Emotional Stability by Personality Type"""

plt.figure(figsize=(8, 4))
sns.violinplot(x='personality_type', y='emotional_stability', data=df, palette='Set1')
plt.title("Emotional Stability by Personality Type")
plt.tight_layout()
plt.show()

"""# Creativity vs. Curiosity Colored by Personality Type"""

plt.figure(figsize=(7, 5))
sns.scatterplot(data=df, x='creativity', y='curiosity', hue='personality_type', alpha=0.6)
plt.title("Creativity vs. Curiosity Colored by Personality Type")
plt.tight_layout()
plt.show()